### ISSUE TITLE
Ordered maps are lost by UI rendering

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1000]
This fiddle has an explicit ordered-map (because there is no pull expression to define column order), but the ordering is lost probably due to (merge) etc

![image](https://user-images.githubusercontent.com/124158/73143263-0270a500-4066-11ea-97fb-68cf8273f9fe.png)
![image](https://user-images.githubusercontent.com/124158/73143273-20d6a080-4066-11ea-8994-530664677bcc.png)

**Comment by Invocatis** [comment]
Easy reproduction:

Add the following to a stage:

[{:db/ident :a, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :b, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :c, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :d, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :e, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :f, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :g, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :h, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :i, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :j, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :k, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}
 {:db/ident :l, :db/cardinality :db.cardinality/one, :db/valueType :db.type/string}]


And the following into the eval window:

[(into (sorted-map) (map (fn [x] [x (name x)]) [:a :b :c :d :e :f :g :h :i :j :k :l]))]

**Comment by dustingetz** [comment]
```clojure
(->> (map (juxt identity name) (contrib.string/abc))
     (take 9)
     (into (sorted-map)))
```

**Comment by Invocatis** [comment]
This issue is being caused by the transit reader/writer. The default behavior for IPersistentMap is to be read as an IPersistentHashMap.

This means, the map is written out in order, but scrambled when read in from transit.

To fix this, we must implement transit readers and writers for each type that is being communicated across the wire. Pull request #1010 adds support for clojure.lang.PersistenTreeMap, which is the class used for sorted-map.

#1010 also adds support for dynamically adding reader/writers via hyperfiddle.transit/register-handler!

**Comment by dustingetz** [comment]
New problem is flatland/ordered-map doesn't have a CLJS implementation
