### ISSUE TITLE
Search params need to support validation specs

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#1081]
Both of the following search prompts need a validation spec (in this case simply `some?`)  as well as a hf/def-validation-message. Not sure if this is trivial.

![image](https://user-images.githubusercontent.com/124158/89111410-73cd4e00-d423-11ea-9c2e-164f509e835a.png)

**Comment by ggeoffrey** [comment]
This is not trivial.
There are multiple issue:
- input fields do not receive their respective value (via props) if the route is invalid (`(not (s/valid? :hyperfiddle/route route))`)
- input fields do not set the new route value if it's invalid, but the check is not performed by the input itself.
- input fields are debounced, and the debounced local state is at a layer where only reagent props are available, not the context. So it's not possible to alter the input group itself.

We need to add a debounced layer at the input-group level. Which implies intercepting on-change events. Adding this layer is not trivial, because of `hf/render` and it's famous `hf/render-dispatch`.

**Comment by ggeoffrey** [comment]
1e3c6282 * Good enough search param spec validation

**Comment by ggeoffrey** [comment]
#1099

**Comment by ggeoffrey** [comment]
Fixed by #1099

**Comment by dustingetz** [comment]
![image](https://user-images.githubusercontent.com/124158/91052748-e7601680-e5ef-11ea-97ef-0c742cdf4137.png)

**Comment by dustingetz** [comment]
There is a bug in hyperfiddle's validation orchestration, as per below repl trace. This is triggered by sub-block use case. If we validate on the hypercrud.browser/route, as compared to validating on hypercrud.browser/route-defaults-symbolic, the explain returns different kinds of errors and hyperfiddle context does not handle it properly in the symbolic case.

```
  (s/fdef school-requested-block :args (s/cat
                                         :school (s/and some? ref?)
                                         :block-reason (s/and some? ref?)
                                         :mode some?
                                         :penalize? boolean?))
  
  (def school [:school/id #uuid "5801550c-c7c6-4e3c-879a-925cd7f70636"])
  (def arg-spec (:args (s/get-spec `school-requested-block)))

  (def route `(swinged.rosie.subs/school-requested-block school nil :force-cancel true))
  (s/explain arg-spec (rest route))
  => nil - failed: some? in: [1] at: [:block-reason]

  (def route' `(swinged.rosie.subs/school-requested-block school))
  (s/explain arg-spec (rest route'))
  => () - failed: Insufficient input at: [:block-reason]
  ; This one hyperfiddle handles wrong, resulting in no invalid styles
```
