### ISSUE TITLE
Flatten hc.b/fes and fields to vector of idents

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#128]
Is this possible?
What features are missing that won't be supported by just a vector of idents?

**Comment by khardenstine** [comment]
- Used to generate fields when user pulls `*` (can just be a conversion of * -> idents)
- parameterized pull expressions shouldn't be a problem (same conversion as `*`)
- fe.splat? is used to determine whether forms show the form/new-field
- Auto binding uri is determined from the fe, would need to re-parse the query to determine the dbname every time for binding
- pull aliasing will need a method to propagate the attr ident along with its alias (hyperfiddle/hyperfiddle.net#106)
- fe type/source-symbol is used for determining auto-link generation
- aggregates and symbol fes still need representation

find-elements and fields aren't going anywhere

**Comment by dustingetz** [comment]
As discussed in person just now, we think the fes are isomorphic to the datalog, we can remove the second find-element abstraction, EXCEPT this could impact performance (computation of the final form structure (aka colspec)) so if that turns out to be the case, we can recode this fe abstraction keeping in mind the idea of it being just an optimization

**Comment by dustingetz** [comment]
This is pretty much paved out in #685, and the rest of the legacy field stuff will migrate organically through targeted issues.
