### ISSUE TITLE
link/class

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#368]
Select :options are the driving need, which specifically need to be able to be data independent (link/path nil), but placed positionally further down the tree (link/class ":body 0 :some-attr")

**Comment by dustingetz** [comment]
Problematic link/formulas that aren't paths but rather code:
* `(fn [ctx] (let [[_ args] (:route ctx)] args))`

Probably need to track all these down, i forgot about them. This one is the user-id from the parent-route, which is a normal input to the parent query but does not pass through the resultset for children. (It could pass through the query in this case since it relates, but now intermediate layers are exposed to the needs of their children, like deep nested UIs)

Idea: there is no formula here, and the ctx is available in the child query, which can query the ctx? This makes sense, because to call `[(hyperfiddle.data/browse ... ctx)]` from datalog obviously requires a ctx.

**Comment by dustingetz** [comment]
http://hyperfiddle.hyperfiddle.net/:hyperfiddle!topnav/~entity('$',(:fiddle!ident,:hyperfiddle!topnav))
```
(fn [ctx] [[:user/user-id @(hyperfiddle.runtime/state (:peer ctx) [:hyperfiddle.runtime/user-id])]])`

(fn [ctx] #entity["$domains" [:domain/ident @(hyperfiddle.runtime/state (:peer ctx) [:hyperfiddle.runtime/domain :domain/ident])]])`

(fn [ctx]
  (let [ctx (assoc ctx :uri @(hyperfiddle.runtime/state (:peer ctx) [:hyperfiddle.runtime/domain :domain/fiddle-database :database/uri]))]
    (hypercrud.browser.auto-link-formula/auto-entity-from-stage ctx)))

(constantly nil)
```

**Comment by khardenstine** [comment]
```clj
(sources/with-sources-conns!
  (fn [conn]
    @(d/transact conn {:db/ident :link/class
                       :db/valueType :db.type/string
                       :db/cardinality :db.cardinality/many})))
```
