### ISSUE TITLE
:xray mode missing [:head]

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#394]
I waffle on this. The story for not drawing them, is that they belong in the top-right corner of the table, which is a tiny little box, and will never actually be drawn there in a real view, they will always be explicitly positioned.

The opposite story is that `http://hyperfiddle.hyperfiddle.net/` has an :account-button popover with the following route: `http://hyperfiddle.hyperfiddle.net/:hyperfiddle.ide!account-button/~entity('$',(:user!user-id,~uuid,'acd054a8-4e36-4d6c-a9ec-95bdc47f0d39'))` Since the view is customized, and it is not drawn in data mode, it was very confusing to understand what route the formula was generating and i had to construct this route by hand. There should be an obvious pink box to click on! (I kept alt-clicking on the *wrong pink box* because i didn't understand the intermediate view happening here and was very very confused for about ten minutes)

Idea: Maybe :xray should probably just look like :api – don't even bother with making it usable, just draw the Datomic results that were hydrated as a flattened list. Let the admins do admin things. They can select options in the raw :db/id renderer by using lookup ref sugar.

**Comment by khardenstine** [comment]
I think I'm misunderstanding this (at least the middle anecdote, maybe you changed something since writing this).
I see a pink box:
![image](https://user-images.githubusercontent.com/7741805/43278152-3935357c-90d8-11e8-98db-cc3ca34f18d7.png)
Clicking it gets that manufactured route:
![image](https://user-images.githubusercontent.com/7741805/43278215-67622392-90d8-11e8-84b9-2c031fa16e88.png)
And here is the sane data mode:
![image](https://user-images.githubusercontent.com/7741805/43278189-522e700c-90d8-11e8-96e5-7b6308c026d2.png)

**Comment by dustingetz** [comment]
Your confusion demonstrates the issue. Find the thing drawing "khardenstine"

**Comment by khardenstine** [comment]
Oh yea I see.  :account is not even [:head] its nil path.  We should draw everything IMO.

This actually somewhat relates to https://github.com/hyperfiddle/hyperfiddle.net/issues/313
I have not thought it out completely yet, but there will be probably be a root level field such that it can pass through to hf.data abstractions.  The root links would then be rendered there.

**Comment by dustingetz** [comment]
Oh I didn't realize nil path was a thing! Should it be a thing?

**Comment by khardenstine** [comment]
Fixed with https://github.com/hyperfiddle/hyperfiddle/commit/28439bcf05545d35ee36be38707428012bd8b0b7
