### ISSUE TITLE
WARN [markdown-extensions:123] -  Error: Assert failed: (string? code-str)

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#519]
- [ ] http://d.hyperfiddle.site/:beta/

![image](https://user-images.githubusercontent.com/124158/44988969-5f902600-af5a-11e8-8918-d04c44decabf.png)

**Comment by khardenstine** [comment]
Strong chance some of these are from #127

**Comment by dustingetz** [comment]
Reverting this because of failed test and fixing differently.

**Comment by dustingetz** [comment]
I think we consider eval a side effect, and thus the call site should handle nil. The markdown extensions are the thing warning and in the future they do need to handle nil at that level.

**Comment by khardenstine** [comment]
I absolutely think the call sites should be handling the nil.
And the markdown extensions should just report the errors directly as DOM rather than writing to console or swallowing exceptions.  See !live extension: https://github.com/hyperfiddle/hyperfiddle/blob/master/src/hyperfiddle/ui/markdown_extensions.cljs#L93-L101

**Comment by khardenstine** [comment]
https://github.com/hyperfiddle/hyperfiddle/commit/d786aaeafd644be1400391d59fc4e980e0ddc93e#r30448291
