### ISSUE TITLE
Bad pull at nested level doesn't show error

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#630]
Note typo in nested level, it should be *owners* not *owner*.

![image](https://user-images.githubusercontent.com/124158/45889187-c9e3fb80-bd8d-11e8-8110-3741130107db.png)

This behavior is probably on purpose, but we should surface it somehow

**Comment by khardenstine** [comment]
1. You have 3 literals in a map, so that error should report (I can reproduce the error surfacing at least)
![image](https://user-images.githubusercontent.com/7741805/45893680-09184980-bd9a-11e8-8417-0201204d2883.png)

2. If you actually meant to omit line 4 and select line 5 in that screenshot, then I assume you have a custom view.  Including an invalid attribute is perfectly valid, and we would surface the field in data mode.
![image](https://user-images.githubusercontent.com/7741805/45893642-e5ed9a00-bd99-11e8-983c-786093e13850.png)

**Comment by khardenstine** [comment]
Ah I see now this is just on pulls
