### ISSUE TITLE
Editing domain/home-route threw away my $ staging area

### ISSUE THREAD

**Issue by dustingetz** [hyperfiddle/hyperfiddle#649]

**Comment by khardenstine** [comment]
Cannot reproduce.  Was this on any specific domain?

Worth noting: since this was reported, the domains db should never have auto-tx set to true and be generally invisible to end users:
https://github.com/hyperfiddle/hypercrud.server/commit/d4eb27fbd78c6b84213b56562e669e5e8b875754#diff-05252a9613633611e05451e253dce87d

**Comment by dustingetz** [comment]
This is probably #619

**Comment by khardenstine** [comment]
Fixed https://github.com/hyperfiddle/hyperfiddle/commit/5232ad069db499d05a09fb124b5360f9fc70efd9
