### ISSUE TITLE
Race condition between fiddle/cljs-ns and markdown f

### ISSUE THREAD

**Issue by khardenstine** [hyperfiddle/hyperfiddle#981]
No longer a forced remount on iframe's (routes can now change).
If the user changes root routes, the iframe may re-use most of the tree, subsequently rendering renderers/markdown before the new cljs-ns evals.  If there is memoization on a symbol (like in our markdown's `!f`directive), the memoized value will be undefined permanently

E.g. nav from, look at team section
http://www2.hyperfiddle.sitecom/
to
http://www2.hyperfiddle.sitecom/:hfinc.www!about/

**Comment by khardenstine** [comment]
Looks like this f! directive should not be using eval or memoization.  If at any point the fIt's arguments are either a function symbol or a keyword.   Rip out memoization and this would be fixed.

**Comment by dustingetz** [comment]
Dustin Getz 2:27 PM
Did the resolve fix work?
Karl Hardenstine 3:14 PM
no
resolve is a macro, also every other memoize-eval has this issue
Dustin Getz 3:35 PM
Do you know where concretely it pops up other than !f
Karl Hardenstine 3:35 PM
i have no example
Dustin Getz 3:35 PM
Do we think link formulas are fucked e.g.
Karl Hardenstine 3:35 PM
yes
practically, it might not be flaring up
but if you used a cljs-ns function in a formula, probably
Dustin Getz 3:35 PM
right
Karl Hardenstine 3:36 PM
i know you have multimethods for a few of them
so the resolve to user content is deferred till pretty late
which is why it probably isnt an issue
im killing two birds with one stone though
im moving hte memoization cache to the domain i think
Dustin Getz 3:37 PM
have you seen core.memoize
Karl Hardenstine 3:37 PM
yea
its clojure only though
and the eval will thread from the ctx
so we can bust the memoize on fiddle values
e.g. cljs-ns
new messages
im trying to figure out what the memoization primatives on the domain and runtime look like right now
Dustin Getz 3:39 PM
ok
